version: '3.3'

services:
  
  sbpdb:
    image: jonesyeh/mssql-2017-dev-sqlfile
    env_file:
      - db_lab.env
    volumes:
      - c:\database\sbp:c:\mssql
    hostname: sbpdb
    networks:
      nd-net:
        ipv4_address: 172.18.0.23
      
  sbpwebapi01:
    image: jonesyeh/sbpwebapi
    env_file:
      - webapi_lab01.env
    volumes:
      - c:\lic:c:\lic
      - c:\log:c:\log
      - C:\ibs:c:\ibs
    hostname: sbpwebapi01
    depends_on:
      - sbpdb
    networks:
      nd-net:
        ipv4_address: 172.18.0.24
  
  sbpwebapi02:
    image: jonesyeh/sbpwebapi
    env_file:
      - webapi_lab02.env
    volumes:
      - c:\lic:c:\lic
      - c:\log:c:\log
      - C:\ibs:c:\ibs
    hostname: sbpwebapi02
    depends_on:
      - sbpwebapi01
    networks:
      nd-net:
        ipv4_address: 172.18.0.25
      
  sbpweb:
    image: jonesyeh/sbpweb
    hostname: sbpweb
    depends_on:
      - sbpwebapi02
    networks:
      nd-net:
        ipv4_address: 172.18.0.21

networks:
  nd-net:
        external:
            name: mynet             