version: '3.7'

services:
  
  sbpdb:
    image: jonesyeh/mssql-2017-dev-sqlfile
    container_name: sbpdb
    env_file:
      - db_lab.env
    volumes:
      - c:\database\sbp:c:\mssql
    hostname: sbpdb
    networks:
      nd-net:
        #ipv4_address: 172.18.0.23
      
  sbpwebapi01:
    image: jonesyeh/sbpwebapi
    container_name: sbpwebapi01  
    env_file:
      - webapi_lab01.env
    volumes:
      - c:\lic:c:\lic
      - c:\log:c:\log
      - C:\ibs:c:\ibs
    hostname: sbpwebapi01
    depends_on:
      - sbpdb
    networks:
      nd-net:
       # ipv4_address: 172.18.0.24
  
  sbpwebapi02:
    image: jonesyeh/sbpwebapi
    container_name: sbpwebapi02   
    env_file:
      - webapi_lab02.env
    volumes:
      - c:\lic:c:\lic
      - c:\log:c:\log
      - C:\ibs:c:\ibs
    hostname: sbpwebapi02
    depends_on:
      - sbpwebapi01
    networks:
      nd-net:
        #ipv4_address: 172.18.0.25
  
  sbpwebapi03:
    image: jonesyeh/sbpwebapi
    container_name: sbpwebapi03   
    env_file:
      - webapi_lab03.env
    volumes:
      - c:\lic:c:\lic
      - c:\log:c:\log
      - C:\ibs:c:\ibs
    hostname: sbpwebapi03
    depends_on:
      - sbpwebapi02
    networks:
      nd-net:
        #ipv4_address: 172.18.0.26
      
  sbpweb:
    image: jonesyeh/sbpweb
    container_name: sbpweb
    hostname: sbpweb
    depends_on:
      - sbpwebapi03
    networks:
      nd-net:
        #ipv4_address: 172.18.0.21

networks:
  nd-net:
        external:
            name: docker              